### PR TITLE
Fix/streamer fails on stream end

### LINKED ISSUE #731: [iOS] Expo App Crash when using StreamerNode when reaching end of stream
> Hi @mdydek! I just started using the library today, and I was looking for this exact thing. I'm currently seeing on `0.9.0` my Expo app crash (Simulator - iPhone 16 - iOS 18.6) when I allow a song to play all the way through, and the `onEnded` callback fires specifically in the `StreamerNode::cleanup()` function when the audio finishes playing. The crash occurs in `std::__1::thread::join()`, which imo suggests the library is trying to join a thread that's already been joined or destroyed. Not an expert but from the Apple crash report, I gather:
> ```
> audioapi::StreamerNode::cleanup() (StreamerNode.cpp:276)
>     ↓
>   std::__1::thread::join()
>     ↓
>   SIGABRT
> ```
> I hope #718 addresses this for iOS as well, since it's fixing callback clearing for `AudioScheduledSourceNode`, which StreamerNode derives from.
> 
> Will look out for `0.10.0` and then test, and if not, open a new bug.
> 
> Thanks! 

 _Originally posted by @jlm0 in [#717](https://github.com/software-mansion/react-native-audio-api/issues/717#issuecomment-3383779080)_

### PR DESCRIPTION
**Pull request by mdydek**
Closes #731 

## Introduced changes

- removed possibility of invoking cleanup from streaming thread
- recompiled ffmpeg with http support

## Checklist

- [ ] Linked relevant issue
- [x] Updated relevant documentation
- [x] Added/Conducted relevant tests
- [ ] Performed self-review of the code
- [ ] Updated Web Audio API coverage
- [ ] Added support for web

### CODE REVIEW

File: packages/react-native-audio-api/common/cpp/audioapi/core/sources/StreamerNode.cpp [hunk 1]
```diff
@@ -44,10 +44,12 @@ bool StreamerNode::initialize(const std::string &input_url) {
   }
 
   if (!openInput(input_url)) {
+    printf("Failed to open input\n");
```
Comment (michalsek) [inline packages/react-native-audio-api/common/cpp/audioapi/core/sources/StreamerNode.cpp]: I would either cleanup those printfs or move popup them to JS layer

Comment (michalsek) [reply packages/react-native-audio-api/common/cpp/audioapi/core/sources/StreamerNode.cpp]: Or hide behind some dev flag
